format = """
$os$username(bg:#313244 fg:#2e3440)\
[](bg:#74c7ec fg:#313244)\
$directory\
[](bg:#94e2d5 fg:#74c7ec)\
$git_branch$git_status\
[](bg:#cba6f7  fg:#94e2d5)\
$deno\
$golang\
$lua\
$nodejs\
[ ](fg:#cba6f7)\
"""

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#2e3440 bg:#94e2d5"

[git_status]
style = "fg:#2e3440 bg:#94e2d5"
format = '[($all_status$ahead_behind )]($style)'

# LANGUAGES
# =========

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#2e3440 bg:#cba6f7"

[golang]
symbol = '󰟓 '
format = '[ $symbol($version )]($style)'
style = "fg:#2e3440 bg:#cba6f7"

[deno]
symbol = 'Deno '
format = '[ $symbol($version )]($style)'
style = "fg:#2e3440 bg:#cba6f7"

[nodejs]
symbol = '󰎙 '
format = "[ $symbol($version )]($style)"
style = "fg:#2e3440 bg:#cba6f7"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#2e3440 bg:#313244"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#cdd6f4 bg:#313244"
disabled = false

[os.symbols]
Arch = '  '
Fedora = '  '
Ubuntu = '  '
Macos = '  '
Pop = '  '

[shell]
disabled = false

[username]
show_always = true
format = '[$user ]($style)'
style_user = "fg:#cdd6f4 bg:#313244"

[directory]
style = "fg:#2e3440 bg:#74c7ec"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#2e3440 bold bg:#74c7ec"

[sudo]
disabled = false
symbol = " "
style = "fg:#2e3440 bg:#d9dee9"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#2e3440 bg:#d9dee9"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"



