format = """
$os$username(bg:#1a1b26 fg:#c0caf5)\
[](bg:#7aa2f7 fg:#1a1b26)\
$directory\
[](bg:#9ece6a fg:#7aa2f7)\
$git_branch$git_status\
[](bg:#f7768e fg:#9ece6a)\
$deno\
$golang\
$lua\
$nodejs\
[ ](fg:#f7768e)\
"""

# GIT
# ===

[git_branch]
format = "[ $symbol$branch(:$remote_branch) ]($style)"
symbol = "󰘬 "
style = "fg:#1a1b26 bg:#9ece6a"

[git_status]
style = "fg:#1a1b26 bg:#9ece6a"
format = '[($all_status$ahead_behind )]($style)'

# LANGUAGES
# =========

[lua]
symbol = '󰢱 '
format = '[ $symbol($version )]($style)'
style = "fg:#1a1b26 bg:#f7768e"

[golang]
symbol = '󰟓 '
format = '[ $symbol($version )]($style)'
style = "fg:#1a1b26 bg:#f7768e"

[deno]
symbol = 'Deno '
format = '[ $symbol($version )]($style)'
style = "fg:#1a1b26 bg:#f7768e"

[nodejs]
symbol = '󰎙 '
format = "[ $symbol($version )]($style)"
style = "fg:#1a1b26 bg:#f7768e"

# MISC
# ====

[hostname]
ssh_only = false
style = "fg:#1a1b26 bg:#1a1b26"
format = "[$ssh_symbol$hostname ]($style)"
ssh_symbol = " "

[os]
style = "fg:#c0caf5 bg:#1a1b26"
disabled = false

[os.symbols]
Arch = '  '
Fedora = '  '
Ubuntu = '  '
Macos = '  '
Pop = '  '

[shell]
disabled = false

[username]
show_always = true
format = '[$user ]($style)'
style_user = "fg:#c0caf5 bg:#1a1b26"

[directory]
style = "fg:#1a1b26 bg:#7aa2f7"
read_only = " "
format = "[ 󰉋 $path ]($style)[$read_only]($read_only_style)"
read_only_style = "fg:#1a1b26 bold bg:#7aa2f7"

[sudo]
disabled = false
symbol = " "
style = "fg:#1a1b26 bg:#c0caf5"
format = "[ $symbol]($style)"

[cmd_duration]
format = "[ 󰔚 $duration ]($style)"
style = "fg:#1a1b26 bg:#c0caf5"

[character]
success_symbol = "[ 󱞩](bold green)"
error_symbol = "[ 󱞩](bold red)"
vimcmd_symbol = "[  󱞩](bold green)"
